import Head from 'next/head'
<<<<<<< HEAD
import styles from '../styles/Home.module.css'
=======
import Landing from '../pages/landing'

import styles from '../styles/index.module.css'
>>>>>>> main

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>UCR IWO Tool</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
<<<<<<< HEAD
        <h1>Test</h1>
=======
        <Landing />
>>>>>>> main
      </>
      

      
    </div>
  )
}